language: ruby
rvm:
  # MRI
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  # Others
  - jruby
  - rbx-3
  - truffleruby
matrix:
  allow_failures:
  - rvm: jruby
  - rvm: rbx-3
  - rvm: truffleruby
script: ruby test_mapgen.rb